spring:
  application:
    name: global-pass
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  supabase:
    url: ${SUPABASE_URL}
    key: ${SUPABASE_KEY}
    bucket: ${SUPABASE_BUCKET:payments}
